spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost/stackers
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
  http:
    multipart:
      maxFileSize: 500MB
jwt:
  secret-key: secret-key-lalala-lululu-fucking-error-WeakKeyException-not-secure-enough
  token-validity-in-sec: 10 # 1??
  refresh-token-validity-in-sec: 604800  # ???
logging:
  level:
    org:
      springframework: INFO
    com:
      ssafy: INFO
server:
  port: '5000'
