spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost/stackers
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  jpa:
    hibernate:
      ddl-auto: 'create'
    show-sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
    generate-ddl: 'true'
  http:
    multipart:
      maxFileSize: 500MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            enable: true
logging:
  level:
    org:
      springframework: INFO
    com:
      ssafy: INFO
      amazonaws:
        util:
          EC2MetadataUtils: ERROR
server:
  port: '5000'

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    syntax-highlight:
      theme: nord
    urls-primary-name: TEST API
    persist-authorization: true
    query-config-enabled: true
  pre-loading-enabled: true
  packages-to-scan: com.ssafy.stackers

